// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package sqlc

import (
	"context"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO Connections (
    id,
    source,
    target
) VALUES (
    ?, ?, ?
)
RETURNING id, source, target
`

type CreateConnectionParams struct {
	ID     string `db:"id" json:"id"`
	Source string `db:"source" json:"source"`
	Target string `db:"target" json:"target"`
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection, arg.ID, arg.Source, arg.Target)
	var i Connection
	err := row.Scan(&i.ID, &i.Source, &i.Target)
	return i, err
}

const getConnections = `-- name: GetConnections :many
SELECT id, source, target FROM Connections
`

func (q *Queries) GetConnections(ctx context.Context) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, getConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(&i.ID, &i.Source, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectionsInvolving = `-- name: GetConnectionsInvolving :many
SELECT id, source, target FROM Connections WHERE source = ? OR target = ?
`

type GetConnectionsInvolvingParams struct {
	Source string `db:"source" json:"source"`
	Target string `db:"target" json:"target"`
}

func (q *Queries) GetConnectionsInvolving(ctx context.Context, arg GetConnectionsInvolvingParams) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, getConnectionsInvolving, arg.Source, arg.Target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(&i.ID, &i.Source, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
