// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flag.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFlag = `-- name: CreateFlag :one
INSERT INTO Flags (
    id,
    flag_type,
    category,
    confidence,
    reviewer,
    is_reportable,
    is_locked,
    queued_at,
    processed_at,
    last_updated,
    reasons
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, flag_type, category, confidence, reviewer, is_reportable, is_locked, queued_at, processed_at, last_updated, reasons, created_at
`

type CreateFlagParams struct {
	ID           string          `db:"id" json:"id"`
	FlagType     string          `db:"flag_type" json:"flag_type"`
	Category     sql.NullString  `db:"category" json:"category"`
	Confidence   sql.NullFloat64 `db:"confidence" json:"confidence"`
	Reviewer     sql.NullString  `db:"reviewer" json:"reviewer"`
	IsReportable sql.NullInt64   `db:"is_reportable" json:"is_reportable"`
	IsLocked     sql.NullInt64   `db:"is_locked" json:"is_locked"`
	QueuedAt     sql.NullString  `db:"queued_at" json:"queued_at"`
	ProcessedAt  sql.NullString  `db:"processed_at" json:"processed_at"`
	LastUpdated  sql.NullString  `db:"last_updated" json:"last_updated"`
	Reasons      sql.NullString  `db:"reasons" json:"reasons"`
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error) {
	row := q.db.QueryRowContext(ctx, createFlag,
		arg.ID,
		arg.FlagType,
		arg.Category,
		arg.Confidence,
		arg.Reviewer,
		arg.IsReportable,
		arg.IsLocked,
		arg.QueuedAt,
		arg.ProcessedAt,
		arg.LastUpdated,
		arg.Reasons,
	)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.FlagType,
		&i.Category,
		&i.Confidence,
		&i.Reviewer,
		&i.IsReportable,
		&i.IsLocked,
		&i.QueuedAt,
		&i.ProcessedAt,
		&i.LastUpdated,
		&i.Reasons,
		&i.CreatedAt,
	)
	return i, err
}

const getFlagByID = `-- name: GetFlagByID :one
SELECT id, flag_type, category, confidence, reviewer, is_reportable, is_locked, queued_at, processed_at, last_updated, reasons, created_at FROM Flags WHERE id = ?
`

func (q *Queries) GetFlagByID(ctx context.Context, id string) (Flag, error) {
	row := q.db.QueryRowContext(ctx, getFlagByID, id)
	var i Flag
	err := row.Scan(
		&i.ID,
		&i.FlagType,
		&i.Category,
		&i.Confidence,
		&i.Reviewer,
		&i.IsReportable,
		&i.IsLocked,
		&i.QueuedAt,
		&i.ProcessedAt,
		&i.LastUpdated,
		&i.Reasons,
		&i.CreatedAt,
	)
	return i, err
}

const getFlags = `-- name: GetFlags :many
SELECT id, flag_type, category, confidence, reviewer, is_reportable, is_locked, queued_at, processed_at, last_updated, reasons, created_at FROM Flags
`

func (q *Queries) GetFlags(ctx context.Context) ([]Flag, error) {
	rows, err := q.db.QueryContext(ctx, getFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flag
	for rows.Next() {
		var i Flag
		if err := rows.Scan(
			&i.ID,
			&i.FlagType,
			&i.Category,
			&i.Confidence,
			&i.Reviewer,
			&i.IsReportable,
			&i.IsLocked,
			&i.QueuedAt,
			&i.ProcessedAt,
			&i.LastUpdated,
			&i.Reasons,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
