// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO Rbx_Groups (Id, Name, Members)
VALUES (?, ?, ?)
RETURNING id, name, members
`

type CreateGroupParams struct {
	ID      string `db:"id" json:"id"`
	Name    string `db:"name" json:"name"`
	Members int64  `db:"members" json:"members"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (RbxGroup, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.ID, arg.Name, arg.Members)
	var i RbxGroup
	err := row.Scan(&i.ID, &i.Name, &i.Members)
	return i, err
}

const getGroupById = `-- name: GetGroupById :one
SELECT id, name, members FROM Rbx_Groups WHERE Id = ?
`

func (q *Queries) GetGroupById(ctx context.Context, id string) (RbxGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupById, id)
	var i RbxGroup
	err := row.Scan(&i.ID, &i.Name, &i.Members)
	return i, err
}

const getGroups = `-- name: GetGroups :many
SELECT id, name, members FROM Rbx_Groups
`

func (q *Queries) GetGroups(ctx context.Context) ([]RbxGroup, error) {
	rows, err := q.db.QueryContext(ctx, getGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RbxGroup
	for rows.Next() {
		var i RbxGroup
		if err := rows.Scan(&i.ID, &i.Name, &i.Members); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupMemberCount = `-- name: UpdateGroupMemberCount :one
UPDATE Rbx_Groups
SET Members = ?
WHERE Id = ?
RETURNING id, name, members
`

type UpdateGroupMemberCountParams struct {
	Members int64  `db:"members" json:"members"`
	ID      string `db:"id" json:"id"`
}

func (q *Queries) UpdateGroupMemberCount(ctx context.Context, arg UpdateGroupMemberCountParams) (RbxGroup, error) {
	row := q.db.QueryRowContext(ctx, updateGroupMemberCount, arg.Members, arg.ID)
	var i RbxGroup
	err := row.Scan(&i.ID, &i.Name, &i.Members)
	return i, err
}
