// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Connection struct {
	ID     string `db:"id" json:"id"`
	Source string `db:"source" json:"source"`
	Target string `db:"target" json:"target"`
}

type Flag struct {
	ID           string          `db:"id" json:"id"`
	FlagType     string          `db:"flag_type" json:"flag_type"`
	Category     sql.NullString  `db:"category" json:"category"`
	Confidence   sql.NullFloat64 `db:"confidence" json:"confidence"`
	Reviewer     sql.NullString  `db:"reviewer" json:"reviewer"`
	IsReportable sql.NullInt64   `db:"is_reportable" json:"is_reportable"`
	IsLocked     sql.NullInt64   `db:"is_locked" json:"is_locked"`
	QueuedAt     sql.NullString  `db:"queued_at" json:"queued_at"`
	ProcessedAt  sql.NullString  `db:"processed_at" json:"processed_at"`
	LastUpdated  sql.NullString  `db:"last_updated" json:"last_updated"`
	Reasons      sql.NullString  `db:"reasons" json:"reasons"`
	CreatedAt    interface{}     `db:"created_at" json:"created_at"`
}

type RbxGroup struct {
	ID      string `db:"id" json:"id"`
	Name    string `db:"name" json:"name"`
	Members int64  `db:"members" json:"members"`
}

type User struct {
	ID      string         `db:"id" json:"id"`
	Name    sql.NullString `db:"name" json:"name"`
	Groupid interface{}    `db:"groupid" json:"groupid"`
	Role    sql.NullString `db:"role" json:"role"`
}
