// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error)
	CreateFlag(ctx context.Context, arg CreateFlagParams) (Flag, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (RbxGroup, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FullUpdateUser(ctx context.Context, arg FullUpdateUserParams) error
	GetConnections(ctx context.Context) ([]Connection, error)
	GetConnectionsInvolving(ctx context.Context, arg GetConnectionsInvolvingParams) ([]Connection, error)
	GetFlagByID(ctx context.Context, id string) (Flag, error)
	GetFlags(ctx context.Context) ([]Flag, error)
	GetGroupById(ctx context.Context, id string) (RbxGroup, error)
	GetGroups(ctx context.Context) ([]RbxGroup, error)
	GetUserById(ctx context.Context, id string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetUsersByGroupId(ctx context.Context, groupid interface{}) ([]User, error)
	UpdateGroupMemberCount(ctx context.Context, arg UpdateGroupMemberCountParams) (RbxGroup, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
}

var _ Querier = (*Queries)(nil)
