// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO Users (Id, Name, GroupId, Role)
VALUES (?, ?, ?, ?)
RETURNING id, name, groupid, role
`

type CreateUserParams struct {
	ID      string         `db:"id" json:"id"`
	Name    sql.NullString `db:"name" json:"name"`
	Groupid interface{}    `db:"groupid" json:"groupid"`
	Role    sql.NullString `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Groupid,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Groupid,
		&i.Role,
	)
	return i, err
}

const fullUpdateUser = `-- name: FullUpdateUser :exec
UPDATE users
SET
Name = ?,
GroupId = ?,
Role = ?
WHERE Id = ?
`

type FullUpdateUserParams struct {
	Name    sql.NullString `db:"name" json:"name"`
	Groupid interface{}    `db:"groupid" json:"groupid"`
	Role    sql.NullString `db:"role" json:"role"`
	ID      string         `db:"id" json:"id"`
}

func (q *Queries) FullUpdateUser(ctx context.Context, arg FullUpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, fullUpdateUser,
		arg.Name,
		arg.Groupid,
		arg.Role,
		arg.ID,
	)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, groupid, role FROM Users WHERE Id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Groupid,
		&i.Role,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, groupid, role FROM Users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Groupid,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByGroupId = `-- name: GetUsersByGroupId :many
SELECT id, name, groupid, role FROM Users WHERE GroupId = ?
`

func (q *Queries) GetUsersByGroupId(ctx context.Context, groupid interface{}) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByGroupId, groupid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Groupid,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE Users
SET Name = ?
WHERE Id = ?
`

type UpdateUserNameParams struct {
	Name sql.NullString `db:"name" json:"name"`
	ID   string         `db:"id" json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserName, arg.Name, arg.ID)
	return err
}
